### ISSUE TITLE
weird color change

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-ocl#16]
Seems the color of the SVG is different from expected. This is in particular shocking in the case of stereo bond. You select a 'abs' (red kind) and it becomes blue.

Seems blue and red are inverted

![2022-08-15 12 27 06](https://user-images.githubusercontent.com/1484241/184619802-58dd8570-6bba-489e-a9c1-5e046da31564.gif)

**Comment by targos** [comment]
You'll have to report that to the original OCL project. We do not control anything about the rendering of the editor area.
