### ISSUE TITLE
StructureEditor never updates when you change initialMolfile or initialIDCode programmatically

### ISSUE THREAD

**Issue by ivorontcov** [zakodium-oss/react-ocl#17]
I created a wrapper that uses some code changes for an initial data structure. I wanted to update the molFile (or IDCode) and expected that once I updated the value - it automatically re-render the component (and structures), but this never happened. It seems like once you set the `initial<something>` it'd never be changed.

I checked the source code but don't see any solutions on how to approach that.

Thoughts?

**Comment by targos** [comment]
We use the special React's `key` prop to reinitialize the editor.
For example: `<StructureEditor key={item.id} initialMolfile={item.molfile} />`.
In the future we might support some way to change the structure without having to do that, but it's not easy to implement correctly.

**Comment by ivorontcov** [comment]
@targos thanks a lot, this is really what I need. Just tested and it works! Closing the thread
