### ISSUE TITLE
Query features missing 'any ring size' drop down menu

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-ocl#20]
In order to test you need to set 'fragment' to true and then to go over an atom and press the `q` key.

![image](https://user-images.githubusercontent.com/1484241/211278163-c7dca379-7e47-449b-af8b-8017b83a3590.png)

The ring size drop down menu is missing. This is the expected preferences:

![image](https://user-images.githubusercontent.com/1484241/211278046-e3404265-7a2b-4bcb-9777-a7d9cb75c4e6.png)

**Comment by targos** [comment]
AFAIK we do nothing in react-ocl related to the QF dialog.

**Comment by targos** [comment]
This is a known issue and will be fixed with the new version based on the GenericEditor API: https://github.com/cheminfo/openchemlib-js/issues/136
