### ISSUE TITLE
Can we have just a SVG without div ?

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-ocl#25]
https://github.com/zakodium-oss/react-ocl/blob/main/src/components/SvgRenderer.js#L78C6-L85

Instead of returning a <div> we could return a svg. This would require to get from the string the <svg> and add all his props.

It would be better if we insert this component in another SVG.

**Comment by targos** [comment]
What do you suggest? The SVG string is already a SVG and we need to render it inside something.
