### ISSUE TITLE
No way to edit atoms on Safari iOs ?

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-ocl#32]
I have no problems to add polycycles but trying to change an atom fails. It looks like it adds systematically an atom rather that replace the existing one.

It would be great to have a link to test the future version and check if this issue is solved.

**Comment by stropitek** [comment]
I've setup build on cloudflare, including previews on PRs:

https://react-ocl.pages.dev

**Comment by targos** [comment]
This is probably unrelated to `react-ocl`. I'm pretty sure OpenChemLib makes actions based on the current hover state. On touch screens there is no hover so when you press the screen, it will always add an atom.

**Comment by targos** [comment]
Honestly I don't know how we can fix this while the entire editor is in Java. It might be possible with the new hybrid version but even that is not sure.

**Comment by targos** [comment]
Fixed by https://github.com/cheminfo/openchemlib-js/pull/206
